//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Highlander2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artifact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artifact()
        {
            this.Version = 1;
            this.EditorRequired = false;
            this.Tag = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Version { get; set; }
        public bool EditorRequired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
        public virtual Directory Directory { get; set; }
    }
}
